---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "openshift-acme-build" 
spec:
  triggers: 
    - type: "ImageChange"
  source: 
    type: "Git"
    git:
      uri: "https://github.com/bartowl/openshift-acme:latest"
  strategy: 
    type: "Docker"
    dockerStrategy:
      dockerfilePath: images/openshift-acme-controller/Dockerfile
  output: 
    to:
      kind: "ImageStreamTag"
      name: "openshift-acme-controller:latest"
---
apiVersion: image.openshift.io/v1
kind: ImageStream
apiVersion: "v1"
metadata:
  name: openshift-acme-controller
spec:
