
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "openshift-acme-build" 
spec:
  triggers: 
    - type: "ImageChange"
  source: 
    type: "Git"
    git:
      uri: "https://github.com/bartowl/openshift-acme"
  strategy: 
    type: "Docker"
    dockerStrategy:
      dockerfilePath: iamges/openshift-acme-controller/Dockerfile
  output: 
    to:
      kind: "ImageStreamTag"
      name: "openshift-acme-controller:latest"